### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by daniel5151** [ainozaki/emu-v1#1]
I know it's still WIP, but there aren't all that many Aarch64 emulators out there, so it'd be neat to possibly play around with this one in my own project(s). Any chance you could add a license?

**Comment by ainozaki** [comment]
Thank you for your suggestion! 👍 
added:
https://github.com/ainozaki/aarch64-emu/blob/master/LICENSE

**Comment by daniel5151** [comment]
Very cool, thanks!
